version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - fastify
  - fillin
  - sonarjs
  - alsa
  - hmss
  - hifi
  - haxor
  - logisoso
  - psevdo
  - mplayer
  - azbuka
  - execa
  - milli
  - numlen
  - helv
  - subdevice
  - scientifica
  - postrender
  - knxt
  - aplay
  - subdevices
ignoreWords: []
import: []
